services:
  - type: web
    name: marketplace-comision-mercadopago
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MP_CLIENT_ID
        sync: false
      - key: MP_CLIENT_SECRET
        sync: false
      - key: BASE_URL
        sync: false
      - key: COMMISSION_PERCENT
        value: "3"
      - key: PORT
        value: "3000"
